name: HourJob

on:
  push:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '3 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: blob
      - name: Create temp dir
        run: |-
          mkdir -p temp
      - name: DNS call sip.borderlesshub.co
        run: |-
          dig sip.borderlesshub.co +short | while read line; do echo "${line}/32"; done > DNS/sip.borderlesshub.co
      - name: DNS call sip.btonephone.net
        run: |-
          dig sip.btonephone.net +short | while read line; do echo "${line}/32"; done > DNS/sip.btonephone.net
      - name: DNS call cybergate.cybertwice.com
        run: |-
          dig cybergate.cybertwice.com +short | grep -E '^[[:digit:]]' | while read line; do echo "${line}/32"; done > DNS/cybergate.cybertwice.com
          dig teams-sipgateway-production-a.cybergate.cybertwice.com +short | grep -E '^[[:digit:]]' | while read line; do echo "${line}/32"; done >> DNS/cybergate.cybertwice.com
          dig teams-sipgateway-production-b.cybergate.cybertwice.com +short | grep -E '^[[:digit:]]' | while read line; do echo "${line}/32"; done >> DNS/cybergate.cybertwice.com
      - name: DNS call ectest.electrocom.dk
        run: |-
          dig ectest.electrocom.dk +short | while read line; do echo "${line}/32"; done > DNS/ectest.electrocom.dk
      - name: DNS call cp-redirect.motorolasolutions.com
        run: |-
          dig cp-redirect.motorolasolutions.com +short | while read line; do echo "${line}/32"; done > DNS/cp-redirect.motorolasolutions.com

      - name: Pull the Block List dshield
        run: |-
          curl "https://feeds.dshield.org/block.txt" -o ./temp/dsblock.txt || true
          ./scripts/dshield-ip-list.py ./temp/dsblock.txt > IOC/dshieldbl.txt

      - name: Pull the Block List Torlist
        run: |-
          curl "https://www.dan.me.uk/torlist/?exit" -o ./temp/exit-nodes.txt || true
          ./scripts/collapse-ip-list.py ./temp/exit-nodes.txt "https://www.dan.me.uk/torlist/?exit" > IOC/exit-nodes.txt

      - name: Pull the IP List SpamHouse
        run: |-
          curl https://www.spamhaus.org/drop/drop.txt | grep -v '^;' | sed -r 's|^([0-9./]*).*|\1|' > IOC/spamhouse-drop.txt
          curl https://www.spamhaus.org/drop/edrop.txt | grep -v '^;' | sed -r 's|^([0-9./]*).*|\1|' > IOC/spamhouse-edrop.txt
          curl https://www.spamhaus.org/drop/dropv6.txt | grep -v '^;' | sed -r 's|^([0-9a-f:/]*).*|\1|' > IOC/spamhouse-dropv6.txt

      - name: Pull the IP List Microsft 365
        run: |-
          mkdir -p MS
          curl https://endpoints.office.com/endpoints/worldwide\?clientrequestid\=b10c5ed1-bad1-445f-b386-b919946339a7 | jq '.[] | select(.serviceArea == "Skype") | .ips[]? ' | awk '!a[$0]++' | sed 's/"//g' > MS/Teams.txt
          curl https://endpoints.office.com/endpoints/worldwide\?clientrequestid\=b10c5ed1-bad1-445f-b386-b919946339a7 | jq '.[] | select(.serviceArea == "Exchange") | .ips[]? ' | awk '!a[$0]++' | sed 's/"//g' > MS/Exchange.txt

      - name: Pull the IP List Git
        run: |-
          mkdir -p git
          curl https://api.github.com/meta > git/raw.git.txt
          strings=$(cat git/raw.git.txt | jq 'keys[]' | grep -v ssh | grep -v verifiable_password_authentication | sed 's/\"//g')
          for i in $strings; do
             echo $i;
             cat git/raw.git.txt | jq '.["'$i'"] | .[] | select(test("^([0-9]{1,3}\\.){3}"))' | sed 's/"//g' > git/github-$i-ipv4.txt;
            cat git/raw.git.txt | jq '.["'$i'"] | .[] | select(test("^(?:[a-fA-F0-9]{1,4}:)"))' | sed 's/"//g' > git/github-$i-ipv6.txt;
          done


      - name: Commit
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "ðŸ¤–: Latest data: ${timestamp}" || exit 0
      - name: Push
        run: |-
          git push
